# Generated by Django 2.2 on 2022-10-21 16:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name="Autor's mame")),
                ('last_name', models.CharField(max_length=100, verbose_name="Autor's last name")),
                ('facebook', models.URLField(null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(null=True, verbose_name='Instagram')),
                ('web', models.URLField(null=True, verbose_name='Web')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('state', models.BooleanField(default=True, verbose_name='State of the autor')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name of the category')),
                ('state', models.BooleanField(default=True, verbose_name='State of the category')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=90, verbose_name='Title')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('image', models.URLField(max_length=255)),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('state', models.BooleanField(default=True, verbose_name='Post/No Post')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
